/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSYSTEM_MEMORY_INTERNALS_H
#define _MOCKSYSTEM_MEMORY_INTERNALS_H

#include "utils/system_memory_internals.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocksystem_memory_internals_Init(void);
void Mocksystem_memory_internals_Destroy(void);
void Mocksystem_memory_internals_Verify(void);


void mock_system_write_impl(S_DATA* dest, S_DATA value);


#define system_init_ExpectAndReturn(base_address, type_size, cmock_retval) system_init_CMockExpectAndReturn(__LINE__, base_address, type_size, cmock_retval)
void system_init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, void* base_address, uint32_t type_size, void* cmock_to_return);
#define system_write_Expect(dest, value) system_write_CMockExpect(__LINE__, dest, value)
void system_write_CMockExpect(UNITY_LINE_TYPE cmock_line, S_DATA* dest, S_DATA value);
#define system_read_ExpectAndReturn(src, cmock_retval) system_read_CMockExpectAndReturn(__LINE__, src, cmock_retval)
void system_read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, S_DATA* src, S_DATA cmock_to_return);

#endif
